version: 6.4.3
title: Paella Player
description: the multistream player for lectures
paella_repository: https://github.com/polimediaupv/paella
timezone: Europe/Madrid
show_downloads: true
google_analytics: UA-26470475-6
markdown: kramdown
highlighter: rouge
baseurl: "/"

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-mentions
  - rouge
collections:
  docs:
    permalink: "/:collection/:path:output_ext"
    output: true   
  demos:
    permalink: "/demos/:title/"
    output: true   
defaults:
  - scope:
      path: "_docs/*"
      type: docs
    values:
      layout: docs
  - scope:
      path: "_demos/*"
      type: demos
    values:
      layout: demo
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_links:
  enabled:     true
  collections: true
